import type { Edge, Shape, ShapeColumn } from "@/lib/types";
import { SHAPE_META } from "@/lib/shapeConfig";

function snake(name: string): string {
  return (
    name
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "") || "item"
  );
}

function singular(name: string): string {
  if (name.endsWith("ies")) return `${name.slice(0, -3)}y`;
  if (name.endsWith("s")) return name.slice(0, -1);
  return name;
}

function sqlType(type: string): string {
  const cleaned = type.trim().toLowerCase().replace(/[^a-z0-9(), ]/g, "");
  if (!cleaned) return "text";
  if (cleaned === "varchar") return "varchar(255)";
  return cleaned;
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

/** Put parent tables before the tables that point to them. */
function orderTables(tables: Shape[], edges: Edge[]): Shape[] {
  const ids = new Set(tables.map((t) => t.id));
  const remaining = [...tables];
  const ordered: Shape[] = [];
  const placed = new Set<string>();

  while (remaining.length > 0) {
    const index = remaining.findIndex((t) =>
      edges
        .filter((e) => e.to === t.id && ids.has(e.from) && e.from !== t.id)
        .every((e) => placed.has(e.from))
    );
    const next = remaining.splice(index === -1 ? 0 : index, 1)[0];
    ordered.push(next);
    placed.add(next.id);
  }
  return ordered;
}

function buildSql(shapes: Shape[], edges: Edge[]): string {
  const tables = orderTables(
    shapes.filter((s) => s.type === "entity"),
    edges
  );
  if (tables.length === 0) return "";

  const byId = new Map(tables.map((t) => [t.id, t]));

  const statements = tables.map((table) => {
    const columns: ShapeColumn[] = table.columns ?? [];
    const pkColumns = columns.filter((c) => c.key === "pk");
    const parents = edges
      .filter((e) => e.to === table.id)
      .map((e) => byId.get(e.from))
      .filter((p): p is Shape => Boolean(p));

    const lines = columns.map((col) => {
      const name = snake(col.name);
      let line = `  ${name} ${sqlType(col.type)}`;
      if (pkColumns.length === 1 && col.key === "pk") line += " PRIMARY KEY";

      if (col.key === "fk") {
        // Guess the parent table from the column name (for example project_id -> projects).
        const parent = parents.find((p) => {
          const parentName = snake(p.label);
          return name === `${singular(parentName)}_id` || name === `${parentName}_id`;
        });
        const parentPk = parent?.columns?.find((c) => c.key === "pk");
        if (parent && parentPk) {
          line += ` REFERENCES ${snake(parent.label)}(${snake(parentPk.name)})`;
        }
      }
      return line;
    });

    if (pkColumns.length > 1) {
      lines.push(`  PRIMARY KEY (${pkColumns.map((c) => snake(c.name)).join(", ")})`);
    }

    return `CREATE TABLE ${snake(table.label)} (\n${lines.join(",\n")}\n);`;
  });

  return statements.join("\n\n");
}

/** A readable Markdown description of everything on the canvas. */
export function buildSpecMarkdown(projectName: string, shapes: Shape[], edges: Edge[]): string {
  const name = projectName.trim() || "Untitled canvas";
  const labelOf = new Map(shapes.map((s) => [s.id, s.label || "(unnamed)"]));
  const components = shapes.filter((s) => s.type !== "entity");
  const tables = shapes.filter((s) => s.type === "entity");

  const out: string[] = [];
  out.push(`# ${name}: design spec`);
  out.push("");
  out.push(`_Generated by Ghost AI on ${new Date().toLocaleDateString()}._`);
  out.push("");
  out.push(
    `${components.length} ${components.length === 1 ? "component" : "components"}, ` +
      `${tables.length} ${tables.length === 1 ? "table" : "tables"}, ` +
      `${edges.length} ${edges.length === 1 ? "connection" : "connections"}.`
  );

  if (components.length > 0) {
    out.push("", "## Components", "");
    out.push("| Name | Type | Technology | Description |");
    out.push("| --- | --- | --- | --- |");
    for (const s of components) {
      const type = SHAPE_META[s.type]?.label ?? s.type;
      out.push(
        `| ${escapeCell(s.label)} | ${type} | ${escapeCell(s.tech ?? "")} | ${escapeCell(
          s.description ?? ""
        )} |`
      );
    }
  }

  if (tables.length > 0) {
    out.push("", "## Database tables");
    for (const t of tables) {
      out.push("", `### ${t.label}`, "");
      out.push("| Column | Type | Key |");
      out.push("| --- | --- | --- |");
      const columns = t.columns ?? [];
      if (columns.length === 0) out.push("| _no columns_ | | |");
      for (const c of columns) {
        out.push(`| ${escapeCell(c.name)} | ${escapeCell(c.type)} | ${c.key ? c.key.toUpperCase() : ""} |`);
      }
    }
  }

  if (edges.length > 0) {
    out.push("", "## Connections", "");
    for (const e of edges) {
      const from = labelOf.get(e.from);
      const to = labelOf.get(e.to);
      if (!from || !to) continue;
      out.push(`- ${from} → ${to}${e.label ? ` (${e.label})` : ""}`);
    }
  }

  const sql = buildSql(shapes, edges);
  if (sql) {
    out.push("", "## SQL (PostgreSQL)", "");
    out.push(
      "Generated from the tables above. Foreign keys are only linked when the column name matches the parent table (for example `project_id` for `projects`). Review before using."
    );
    out.push("", "```sql", sql, "```");
  }

  if (shapes.length === 0) {
    out.push("", "_The canvas is empty._");
  }

  return out.join("\n") + "\n";
}

/** Download text as a file in the browser. */
export function downloadText(filename: string, text: string, mime = "text/markdown"): void {
  const blob = new Blob([text], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}